### ISSUE TITLE
Slashers GitHub version

### ISSUE THREAD

**Issue by Azukiiii** [Garrus2142/Slashers#63]
Hi, I'm using the workshop version of slashers and I got problems on ghostface with his ability. I saw that a knew version of slashers was on github but I don't know how to install it. Thanks

**Comment by Dust911** [comment]
Same. Me either don't know where should i mount the files

**Comment by Azukiiii** [comment]
Can somebody help @Guilhem-Pech @Garrus2142 ?

**Comment by Guilhem-Pech** [comment]
Hello, sorry for keeping you waiting, in order to download the GitHub version you just have to click here 
![image](https://user-images.githubusercontent.com/15714248/118406081-2ef56980-b67b-11eb-950f-c8abe27aeb5f.png)
And to put the the content in the Gamemode folder (Steam\steamapps\common\GarrysMod\garrysmod\gamemodes\slashers)
